### ISSUE TITLE
Show list of notarizations (on-chain) 

### ISSUE THREAD

**Issue by eckelj** [rddl-network/EnergyAgent#29]

**Comment by Cybnon** [comment]
there is now a table that shows notarizations transactions and their corresponding CIDs
![Screenshot 2024-05-28 at 09 24 28](https://github.com/rddl-network/EnergyAgent/assets/8808492/1bd0ec92-2c27-4fb1-ae02-ec6871727a68)
![Screenshot 2024-05-28 at 09 24 22](https://github.com/rddl-network/EnergyAgent/assets/8808492/03d40e74-2bec-4c50-bdf3-3a730c74f16c)
