### ISSUE TITLE
Add Interface to store CIDs also on IPFS

### ISSUE THREAD

**Issue by Cybnon** [rddl-network/EnergyAgent#34]
Currently the Energy Agent stores CIDs locally but should also be able to distribute the storage of the CID to IPFS as well

**Comment by GR3G0RYO** [comment]
@Cybnon what is the use case for the need for this?

**Comment by GR3G0RYO** [comment]
I will reach out to Stefan and discuss

**Comment by GR3G0RYO** [comment]
Still valid just and needs to worked on when time allows.
